name: project_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"  # Updated SDK constraint to reflect supported versions

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9  # Calendar package for your project
  shared_preferences: ^2.2.2  # To store simple data locally
  cupertino_icons: ^1.0.8  # Cupertino Icons package for iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Recommended lint package for good coding practices

flutter:
  uses-material-design: true  # This ensures Material Design icons are available in the project

  # Uncomment and specify the paths for assets if you need to include them:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment and customize the fonts section if you wish to add custom fonts:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  # For adding assets from package dependencies, refer to Flutter documentation:
  # https://flutter.dev/docs/development/packages-and-plugins/using-packages
